
package com.reactiveworks.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OperationImpl", targetNamespace = "http://services.reactiveworks.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OperationImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.reactiveworks.client.NewOperationResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newOperation", targetNamespace = "http://services.reactiveworks.com/", className = "com.reactiveworks.client.NewOperation")
    @ResponseWrapper(localName = "newOperationResponse", targetNamespace = "http://services.reactiveworks.com/", className = "com.reactiveworks.client.NewOperationResponse")
    @Action(input = "http://services.reactiveworks.com/OperationImpl/newOperationRequest", output = "http://services.reactiveworks.com/OperationImpl/newOperationResponse")
    public com.reactiveworks.client.NewOperationResponse.Return newOperation(
        @WebParam(name = "arg0", targetNamespace = "")
        com.reactiveworks.client.NewOperation.Arg0 arg0);

}
