
package com.reactiveworks.product.service.client;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductServiceImpl", targetNamespace = "http://service.product.reactiveworks.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.reactiveworks.product.service.client.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListOfProductFromProductType", targetNamespace = "http://service.product.reactiveworks.com/", className = "com.reactiveworks.product.service.client.GetListOfProductFromProductType")
    @ResponseWrapper(localName = "getListOfProductFromProductTypeResponse", targetNamespace = "http://service.product.reactiveworks.com/", className = "com.reactiveworks.product.service.client.GetListOfProductFromProductTypeResponse")
    @Action(input = "http://service.product.reactiveworks.com/ProductServiceImpl/getListOfProductFromProductTypeRequest", output = "http://service.product.reactiveworks.com/ProductServiceImpl/getListOfProductFromProductTypeResponse")
    public List<Product> getListOfProductFromProductType(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
