
package com.reactiveworks.services;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "operation", targetNamespace = "http://www.example.org/operation/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Operation {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.reactiveworks.services.AddResponse
     */
    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/operation/NewOperation")
    @WebResult(name = "AddResponse", targetNamespace = "http://www.example.org/operation/", partName = "parameters")
    public AddResponse newOperation(
        @WebParam(name = "Add", targetNamespace = "http://www.example.org/operation/", partName = "parameters")
        Add parameters);

}
