
package com.reactiveworks.cxf.example.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.13
 * Mon Jul 24 10:22:02 IST 2023
 * Generated source version: 2.0.13
 * 
 */

@XmlRootElement(name = "getAdd", namespace = "http://example.cxf.reactiveworks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAdd", namespace = "http://example.cxf.reactiveworks.com/")

public class GetAdd {

    @XmlElement(name = "a")
    private int a;
    @XmlElement(name = "b")
    private int b;

    public int getA() {
        return this.a;
    }
    
    public void setA( int newA ) {
        this.a = newA;
    }
    
    public int getB() {
        return this.b;
    }
    
    public void setB( int newB ) {
        this.b = newB;
    }
    
}

