
package com.reactiveworks.cxf.example.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.13
 * Mon Jul 24 10:22:02 IST 2023
 * Generated source version: 2.0.13
 * 
 */

@XmlRootElement(name = "getFactorial", namespace = "http://example.cxf.reactiveworks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getFactorial", namespace = "http://example.cxf.reactiveworks.com/")

public class GetFactorial {

    @XmlElement(name = "n")
    private int n;

    public int getN() {
        return this.n;
    }
    
    public void setN( int newN ) {
        this.n = newN;
    }
    
}

