
package com.reactiveworks.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Operations", targetNamespace = "http://cxf.reactiveworks.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Operations {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAdd", targetNamespace = "http://cxf.reactiveworks.com/", className = "com.reactiveworks.cxf.GetAdd")
    @ResponseWrapper(localName = "getAddResponse", targetNamespace = "http://cxf.reactiveworks.com/", className = "com.reactiveworks.cxf.GetAddResponse")
    public int getAdd(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
