
package com.reactiveworks.product.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "productService", targetNamespace = "http://www.example.org/productService/", wsdlLocation = "file:/S:/WorkSpace/FileHandling/TopDown-Tomcat10-JakartaEE9-ProductExercise/productService.wsdl")
public class ProductService_Service
    extends Service
{

    private final static URL PRODUCTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTSERVICE_EXCEPTION;
    private final static QName PRODUCTSERVICE_QNAME = new QName("http://www.example.org/productService/", "productService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/S:/WorkSpace/FileHandling/TopDown-Tomcat10-JakartaEE9-ProductExercise/productService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTSERVICE_WSDL_LOCATION = url;
        PRODUCTSERVICE_EXCEPTION = e;
    }

    public ProductService_Service() {
        super(__getWsdlLocation(), PRODUCTSERVICE_QNAME);
    }

    public ProductService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTSERVICE_QNAME, features);
    }

    public ProductService_Service(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTSERVICE_QNAME);
    }

    public ProductService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTSERVICE_QNAME, features);
    }

    public ProductService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "productServiceSOAP")
    public ProductService getProductServiceSOAP() {
        return super.getPort(new QName("http://www.example.org/productService/", "productServiceSOAP"), ProductService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "productServiceSOAP")
    public ProductService getProductServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/productService/", "productServiceSOAP"), ProductService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTSERVICE_EXCEPTION!= null) {
            throw PRODUCTSERVICE_EXCEPTION;
        }
        return PRODUCTSERVICE_WSDL_LOCATION;
    }

}
