
package com.reactiveworks.product.service;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "productService", targetNamespace = "http://www.example.org/productService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @param productType
     * @return
     *     returns java.util.List<com.reactiveworks.product.service.Product>
     */
    @WebMethod(action = "http://www.example.org/productService/getListOfProductFromProductType")
    @WebResult(name = "listOfProduct", targetNamespace = "")
    @RequestWrapper(localName = "getListOfProductFromProductType", targetNamespace = "http://www.example.org/productService/", className = "com.reactiveworks.product.service.GetListOfProductFromProductType")
    @ResponseWrapper(localName = "getListOfProductFromProductTypeResponse", targetNamespace = "http://www.example.org/productService/", className = "com.reactiveworks.product.service.GetListOfProductFromProductTypeResponse")
    public List<Product> getListOfProductFromProductType(
        @WebParam(name = "productType", targetNamespace = "")
        String productType);

}
